### ISSUE TITLE
[Infrastructure] Setup continuous delivery for Chrome Web Store - Part 1

### ISSUE THREAD

**Issue by rohithbalaji123** [short-d/short-ext#29]
Sub Issue of #28 

#### Tasks:
- [x] Replace version in manifest.json with an environmental variable.
- [x] Update the build script to pass TAG env as VERSION env.
- [x] Create Drone CI configuration (https://github.com/short-d/short/blob/master/.drone.yml) to listen to tag event and pass DRONE_TAG to the build script.
